### ISSUE TITLE
Toxic preview

### ISSUE THREAD

**Issue by Jakeukalane** [wrapperband/evolvotron#1]
Explanations at http://web.archive.org/web/20161013043047/http://www.bottlenose.net/share/evolvotron/index.htm  were very useful so I wonder if they could be incorporated here, along with the Toxic preview jar (http://web.archive.org/web/20150915114003/http://www.bottlenose.net/java/toxic/toxic.jar)
that is nowhere to be found.

Thank you and sorry if this is not the correct to contact.

**Comment by wrapperband** [comment]
Thanks, this is just a historical set-up - it worked as is - so it isn't maintained. You could fork it and add the extra (toxic? jar).

**Comment by Jakeukalane** [comment]
I don't have it. I was asking if you have it. It is a prototype of evolvotron. Maybe is interesting also for historical reasons. I thought you were the original coder.
Thank you anyway

**Comment by wrapperband** [comment]
Sorry, I wasn't plain. I don't think I got it from where you're indicating -, all I have is on Github.

**Comment by Jakeukalane** [comment]
No problem, thank you!
